import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // App name
    appName: "MazhalaiValam",
    appSubtitle: "Child Health Monitoring System",
    appTagline: "மழலைவளம்",

    // Auth
    login: "Sign In",
    register: "Register",
    username: "Username",
    password: "Password",
    role: "Role",
    logout: "Logout",
    show: "Show",
    hide: "Hide",
    enterUsername: "Enter your username",
    enterPassword: "Enter your password",
    createAccount: "Create Account",
    joinSystem: "Join MazhalaiValam System",
    createUsername: "Enter a username",
    createPassword: "Create a password",
    nameEn: "Name (English)",
    nameTa: "Name (Tamil)",
    enterNameEn: "Enter full name (English)",
    enterNameTa: "Enter full name (Tamil)",
    alreadyHaveAccount: "Already have an account?",
    signInHere: "Sign in here",
    dontHaveAccount: "Don't have an account?",
    registerHere: "Register here",
    demoCredentials: "Demo Credentials:",
    admin: "Admin",
    parent: "Parent",
    invalidCredentials: "Invalid username or password. Please try again.",
    parentRegistrationNote: "Parent Registration: Please use the username provided to you by the Anganwadi Admin when your child was registered.",
    loading: "Loading...",

    // Sidebar
    dashboard: "Dashboard",
    addChild: "Add Child",
    childManagement: "Child Management",
    attendance: "Attendance",
    reports: "Reports",
    administrator: "Administrator",
    adminPanel: "Admin Panel",

    // Dashboard
    dashboardOverview: "Dashboard Overview",
    dashboardSubtitle: "MazhalaiValam Child Health Monitoring",
    totalChildren: "Total Children",
    normal: "Normal",
    needsAttention: "Needs Attention",
    underweight: "Underweight",
    absenceAlerts: "Absence Alerts",
    absentFor: "Absent for",
    day: "day",
    days: "days",
    view: "View",
    quickActions: "Quick Actions",
    addChildBtn: "Add Child",
    markAttendance: "Mark Attendance",
    viewChildren: "View Children",
    viewReports: "View Reports",
    childrenOverview: "Children Overview",
    name: "Name",
    age: "Age",
    weight: "Weight (kg)",
    status: "Status",
    action: "Action",
    details: "Details",
    yrs: "yrs",

    // Add Child
    addNewChild: "Add New Child",
    addChildSubtitle: "Register a child into the monitoring system",
    childAddedSuccess: "Child added successfully.",
    childName: "Child Name *",
    childNameEn: "Child Name (English) *",
    childNameTa: "Child Name (Tamil)",
    fullName: "Full name",
    fullNameEn: "Full name (English)",
    fullNameTa: "முழு பெயர் (Tamil)",
    ageYears: "Age (years) *",
    ageEg: "e.g. 3",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    parentName: "Parent Name *",
    parentNameEn: "Parent Name (English) *",
    parentNameTa: "Parent Name (Tamil)",
    parentGuardianName: "Parent / Guardian name",
    parentGuardianNameEn: "Parent / Guardian name (English)",
    parentGuardianNameTa: "பெற்றோர் பெயர் (Tamil)",
    parentUsername: "Parent Username *",
    parentLoginUsername: "Login username for parent",
    heightCm: "Height (cm) *",
    heightEg: "e.g. 88.5",
    weightKg: "Weight (kg) *",
    weightEg: "e.g. 12.3",
    healthNotes: "Symptoms / Health Notes",
    healthNotesPlaceholder: "Enter any symptoms or additional health notes about the child...",
    cancel: "Cancel",
    addChildSubmit: "Add Child",

    // Child Management
    childManagementTitle: "Child Management",
    childManagementSubtitle: "View and manage all registered children",
    searchByName: "Search by name...",
    all: "All",
    noChildrenFound: "No children found matching your criteria.",
    height: "Height",
    alerts: "alerts",
    alert: "alert",

    // Attendance
    attendanceTitle: "Attendance",
    attendanceSubtitle: "Mark attendance and schedule next visits for all children",
    filterByDate: "Filter by Date:",
    present: "Present",
    absent: "Absent",
    attendanceDate: "Attendance Date",
    dayLabel: "Day",
    nextVisitDate: "Next Visit Date",
    absentDaysTotal: "Absent {n} days total",
    attendanceRecordsFor: "Attendance Records for",
    noAttendanceRecords: "No attendance records for",
    childName2: "Child Name",
    date: "Date",
    dayCol: "Day",

    // Reports
    reportsTitle: "Reports",
    reportsSubtitle: "Health and attendance summary for all children",
    priorityActionList: "Priority Action List",
    underweightChildren: "Underweight Children",
    needsAttentionSection: "Needs Attention",
    frequentlyAbsent: "Frequently Absent Children",
    noIssues: "No issues found in this category.",
    weightLabel: "Weight:",
    absentDays: "Absent days:",
    priorityScore: "Priority Score:",
    viewDetails: "View Details",
    absentDaysCount: "Absent {n} days",

    // Child Details
    editChildDetails: "Edit Child Details",
    updateInfoFor: "Update information for",
    back: "← Back",
    editChild: "Edit Child",
    deleteChild: "Delete Child",
    childNotFound: "Child not found.",
    deleteConfirm: "Are you sure you want to delete this child?",
    growthMeasurements: "Growth Measurements",
    previousValues: "Previous: Height",
    attendanceCard: "Attendance",
    daysAbsent: "Days Absent",
    today: "Today:",
    noRecord: "No record",
    nextVisit: "Next Visit Date",
    attendanceHistory: "Attendance History",
    noHistory: "No history available.",
    activeAlerts: "Active Alerts",
    symptomsHealthNotes: "Symptoms / Health Notes",
    nutritionSuggestion: "Nutrition Suggestion",
    vaccinationRecord: "Vaccination Record",
    noVaccinationRecords: "No vaccination records available.",
    completed: "Completed",
    pending: "Pending",
    markDone: "Mark Done",
    markUndone: "Mark Undone",
    done: "Done",
    vaccineName: "Vaccine Name",
    vaccineNamePlaceholder: "e.g., Polio",
    add: "Add",
    update: "Update",
    removeVaccineConfirm: "Are you sure you want to remove this vaccination record?",
    noRecords: "No records available.",
    dateLabel: "Date",

    // Parent Dashboard
    smartAnganwadi: "MazhalaiValam",
    loadingChildData: "Loading child data...",
    noChildLinked: "No child record linked to your account.",
    welcome: "Welcome,",
    yearsOld: "years",
    dob: "DOB:",
    notAvailable: "N/A",
    growthCard: "Growth Measurements",
    heightLabel: "Height",
    weightLabelP: "Weight",
    todayStatus: "Today:",
    nextVisitDateP: "Next Visit Date",
    attendanceHistoryP: "Attendance History",
    alertsCard: "Alerts",
    nutritionCard: "Nutrition Suggestion",
    vaccinationCard: "Vaccination Record",

    // Status Badge
    statusNormal: "Normal",
    statusAttention: "Needs Attention",
    statusUnderweight: "Underweight",

    // Language switcher
    language: "Language",
    english: "English",
    tamil: "Tamil",
  },

  ta: {
    // App name
    appName: "மழலைவளம்",
    appSubtitle: "குழந்தை சுகாதார கண்காணிப்பு அமைப்பு",
    appTagline: "MazhalaiValam",

    // Auth
    login: "உள்நுழை",
    register: "பதிவு செய்",
    username: "பயனர்பெயர்",
    password: "கடவுச்சொல்",
    role: "பாத்திரம்",
    logout: "வெளியேறு",
    show: "காட்டு",
    hide: "மறை",
    enterUsername: "உங்கள் பயனர்பெயரை உள்ளிடவும்",
    enterPassword: "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
    createAccount: "கணக்கை உருவாக்கு",
    joinSystem: "மழலைவளம் அமைப்பில் சேர",
    createUsername: "பயனர்பெயரை உள்ளிடவும்",
    createPassword: "கடவுச்சொல்லை உருவாக்கவும்",
    nameEn: "பெயர் (ஆங்கிலம்)",
    nameTa: "பெயர் (தமிழ்)",
    enterNameEn: "முழு பெயரை உள்ளிடவும் (ஆங்கிலம்)",
    enterNameTa: "முழு பெயரை உள்ளிடவும் (தமிழ்)",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    signInHere: "இங்கே உள்நுழையவும்",
    dontHaveAccount: "கணக்கு இல்லையா?",
    registerHere: "இங்கே பதிவு செய்யவும்",
    demoCredentials: "டெமோ நற்சான்றுகள்:",
    admin: "நிர்வாகி",
    parent: "பெற்றோர்",
    invalidCredentials: "தவறான பயனர்பெயர் அல்லது கடவுச்சொல். மீண்டும் முயற்சிக்கவும்.",
    parentRegistrationNote: "பெற்றோர் பதிவு: உங்கள் குழந்தை பதிவு செய்யப்பட்டபோது அங்கன்வாடி நிர்வாகி வழங்கிய பயனர்பெயரை பயன்படுத்தவும்.",
    loading: "ஏற்றுகிறது...",

    // Sidebar
    dashboard: "டாஷ்போர்டு",
    addChild: "குழந்தையை சேர்",
    childManagement: "குழந்தை மேலாண்மை",
    attendance: "வருகைப்பதிவு",
    reports: "அறிக்கைகள்",
    administrator: "நிர்வாகி",
    adminPanel: "நிர்வாக பலகை",

    // Dashboard
    dashboardOverview: "டாஷ்போர்டு கண்ணோட்டம்",
    dashboardSubtitle: "மழலைவளம் குழந்தை சுகாதார கண்காணிப்பு",
    totalChildren: "மொத்த குழந்தைகள்",
    normal: "சாதாரண",
    needsAttention: "கவனம் தேவை",
    underweight: "குறைந்த எடை",
    absenceAlerts: "வருகை எச்சரிக்கைகள்",
    absentFor: "வராத நாட்கள்",
    day: "நாள்",
    days: "நாட்கள்",
    view: "காண்க",
    quickActions: "விரைவு செயல்கள்",
    addChildBtn: "குழந்தையை சேர்",
    markAttendance: "வருகை பதிவு",
    viewChildren: "குழந்தைகளை காண்க",
    viewReports: "அறிக்கைகளை காண்க",
    childrenOverview: "குழந்தைகள் கண்ணோட்டம்",
    name: "பெயர்",
    age: "வயது",
    weight: "எடை (கிலோ)",
    status: "நிலை",
    action: "செயல்",
    details: "விவரங்கள்",
    yrs: "ஆண்டு",

    // Add Child
    addNewChild: "புதிய குழந்தையை சேர்",
    addChildSubtitle: "கண்காணிப்பு அமைப்பில் குழந்தையை பதிவு செய்யவும்",
    childAddedSuccess: "குழந்தை வெற்றிகரமாக சேர்க்கப்பட்டது.",
    childName: "குழந்தையின் பெயர் *",
    childNameEn: "குழந்தையின் பெயர் (ஆங்கிலம்) *",
    childNameTa: "குழந்தையின் பெயர் (தமிழ்)",
    fullName: "முழு பெயர்",
    fullNameEn: "முழு பெயர் (ஆங்கிலம்)",
    fullNameTa: "முழு பெயர் (தமிழ்)",
    ageYears: "வயது (ஆண்டுகள்) *",
    ageEg: "எ.கா. 3",
    dateOfBirth: "பிறந்த தேதி",
    gender: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    parentName: "பெற்றோர் பெயர் *",
    parentNameEn: "பெற்றோர் பெயர் (ஆங்கிலம்) *",
    parentNameTa: "பெற்றோர் பெயர் (தமிழ்)",
    parentGuardianName: "பெற்றோர் / பாதுகாவலர் பெயர்",
    parentGuardianNameEn: "பெற்றோர் / பாதுகாவலர் பெயர் (ஆங்கிலம்)",
    parentGuardianNameTa: "பெற்றோர் / பாதுகாவலர் பெயர் (தமிழ்)",
    parentUsername: "பெற்றோர் பயனர்பெயர் *",
    parentLoginUsername: "பெற்றோருக்கான உள்நுழைவு பயனர்பெயர்",
    heightCm: "உயரம் (செ.மீ) *",
    heightEg: "எ.கா. 88.5",
    weightKg: "எடை (கிலோ) *",
    weightEg: "எ.கா. 12.3",
    healthNotes: "அறிகுறிகள் / சுகாதார குறிப்புகள்",
    healthNotesPlaceholder: "குழந்தையின் அறிகுறிகள் அல்லது கூடுதல் சுகாதார குறிப்புகளை உள்ளிடவும்...",
    cancel: "ரத்து செய்",
    addChildSubmit: "குழந்தையை சேர்",

    // Child Management
    childManagementTitle: "குழந்தை மேலாண்மை",
    childManagementSubtitle: "அனைத்து பதிவு செய்யப்பட்ட குழந்தைகளையும் பார்க்கவும் மேலாண்மை செய்யவும்",
    searchByName: "பெயரால் தேடவும்...",
    all: "அனைத்தும்",
    noChildrenFound: "உங்கள் தேர்வுகளுக்கு பொருந்தும் குழந்தைகள் இல்லை.",
    height: "உயரம்",
    alerts: "எச்சரிக்கைகள்",
    alert: "எச்சரிக்கை",

    // Attendance
    attendanceTitle: "வருகைப்பதிவு",
    attendanceSubtitle: "அனைத்து குழந்தைகளுக்கும் வருகை பதிவிடவும் அடுத்த வருகையை திட்டமிடவும்",
    filterByDate: "தேதியால் வடிகட்டவும்:",
    present: "வந்தார்",
    absent: "வரவில்லை",
    attendanceDate: "வருகை தேதி",
    dayLabel: "நாள்",
    nextVisitDate: "அடுத்த வருகை தேதி",
    absentDaysTotal: "{n} நாட்கள் வரவில்லை",
    attendanceRecordsFor: "வருகை பதிவுகள்",
    noAttendanceRecords: "வருகை பதிவுகள் இல்லை",
    childName2: "குழந்தையின் பெயர்",
    date: "தேதி",
    dayCol: "நாள்",

    // Reports
    reportsTitle: "அறிக்கைகள்",
    reportsSubtitle: "அனைத்து குழந்தைகளுக்கும் சுகாதார மற்றும் வருகை சுருக்கம்",
    priorityActionList: "முன்னுரிமை செயல் பட்டியல்",
    underweightChildren: "குறைந்த எடை குழந்தைகள்",
    needsAttentionSection: "கவனம் தேவை",
    frequentlyAbsent: "அடிக்கடி வராத குழந்தைகள்",
    noIssues: "இந்த வகையில் பிரச்சனைகள் இல்லை.",
    weightLabel: "எடை:",
    absentDays: "வராத நாட்கள்:",
    priorityScore: "முன்னுரிமை மதிப்பெண்:",
    viewDetails: "விவரங்களை காண்க",
    absentDaysCount: "{n} நாட்கள் வரவில்லை",

    // Child Details
    editChildDetails: "குழந்தை விவரங்களை திருத்து",
    updateInfoFor: "இதற்கான தகவலை புதுப்பி",
    back: "← திரும்பு",
    editChild: "குழந்தையை திருத்து",
    deleteChild: "குழந்தையை நீக்கு",
    childNotFound: "குழந்தை கிடைக்கவில்லை.",
    deleteConfirm: "இந்த குழந்தையை நீக்க வேண்டுமா?",
    growthMeasurements: "வளர்ச்சி அளவீடுகள்",
    previousValues: "முந்தைய: உயரம்",
    attendanceCard: "வருகைப்பதிவு",
    daysAbsent: "வராத நாட்கள்",
    today: "இன்று:",
    noRecord: "பதிவு இல்லை",
    nextVisit: "அடுத்த வருகை தேதி",
    attendanceHistory: "வருகை வரலாறு",
    noHistory: "வரலாறு இல்லை.",
    activeAlerts: "செயலில் உள்ள எச்சரிக்கைகள்",
    symptomsHealthNotes: "அறிகுறிகள் / சுகாதார குறிப்புகள்",
    nutritionSuggestion: "ஊட்டச்சத்து பரிந்துரை",
    vaccinationRecord: "தடுப்பூசி பதிவு",
    noVaccinationRecords: "தடுப்பூசி பதிவுகள் இல்லை.",
    completed: "முடிந்தது",
    pending: "நிலுவையில்",
    markDone: "முடிந்தது என குறி",
    markUndone: "முடியவில்லை என குறி",
    done: "முடிந்தது",
    vaccineName: "தடுப்பூசி பெயர்",
    vaccineNamePlaceholder: "எ.கா., போலியோ",
    add: "சேர்",
    update: "புதுப்பி",
    removeVaccineConfirm: "இந்த தடுப்பூசி பதிவை நீக்க வேண்டுமா?",
    noRecords: "பதிவுகள் இல்லை.",
    dateLabel: "தேதி",

    // Parent Dashboard
    smartAnganwadi: "மழலைவளம்",
    loadingChildData: "குழந்தை தரவு ஏற்றுகிறது...",
    noChildLinked: "உங்கள் கணக்குடன் இணைக்கப்பட்ட குழந்தை பதிவு இல்லை.",
    welcome: "வணக்கம்,",
    yearsOld: "ஆண்டுகள்",
    dob: "பிறந்த தேதி:",
    notAvailable: "கிடைக்கவில்லை",
    growthCard: "வளர்ச்சி அளவீடுகள்",
    heightLabel: "உயரம்",
    weightLabelP: "எடை",
    todayStatus: "இன்று:",
    nextVisitDateP: "அடுத்த வருகை தேதி",
    attendanceHistoryP: "வருகை வரலாறு",
    alertsCard: "எச்சரிக்கைகள்",
    nutritionCard: "ஊட்டச்சத்து பரிந்துரை",
    vaccinationCard: "தடுப்பூசி பதிவு",

    // Status Badge
    statusNormal: "சாதாரண",
    statusAttention: "கவனம் தேவை",
    statusUnderweight: "குறைந்த எடை",

    // Language switcher
    language: "மொழி",
    english: "English",
    tamil: "தமிழ்",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("mv_lang") || "en");

  function switchLanguage(newLang) {
    setLang(newLang);
    localStorage.setItem("mv_lang", newLang);
  }

  const t = translations[lang] || translations.en;

  function formatName(nameEn, nameTa) {
    if (!nameTa) return nameEn;
    return lang === "ta" ? `${nameTa} (${nameEn})` : `${nameEn} (${nameTa})`;
  }

  return (
    <LanguageContext.Provider value={{ lang, switchLanguage, t, formatName }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
